version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: car_rental_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental
      MYSQL_USER: teste
      MYSQL_PASSWORD: senhaTeste
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databaseSchemas:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: